PHRTAB FDB    BADDMP                                                     0
       FDB    OKMP    PHRASE 16 INITIAL TESTS...                         1
       FDB    RERRMP  PHRASE 17 RAM ERROR                                2
       FDB    ROMERP  PHRASE 18 ROM ERROR                                3
       FDB    ROMOKP  PHRASE 25 ALL ROMS OK ETC                          4
       FDB    RAMOKP  PHRASE 26 NO RAM ERRORS DETECTED                   5
       FDB    CMOKP   PHRASE 27 BATTERY RAM OK                           6
       FDB    CMERRP  PHRASE 28 BATTERY RAM ERROR                        7
       FDB    CMDORP  PHRASE 29 BATTERY ROM, OR WRITE PROTECT CIRCUIT    8
       FDB    SNDTEP  PHRASE 30 SOUND LINE X                             9
       FDB    FDROMP  PHRASE 31 FRONT DOOR ROM ERROR                    10 
       FDB    FDRAMP  PHRASE 32 FRONT DOOR RAM ERROR                    11
       FDB    SWTSTP  PHRASE 33 SWITCH TEST                             12
       FDB    SZAUP   AUTO UP               34                          13
       FDB    SZADV    ADV                  35                          14
       FDB    SZRC     RIGHT COIN           36                          15
       FDB    SZHSR    HIGH SCORE RESET     37                          16
       FDB    SZLC     LEFT COIN            38                          17
       FDB    SZCC     CENTER COIN          39                          18
       FDB    SZSS     SLAM SWITCH          40                          19
       FDB    SZFIRE   FIRE MESSAGE         41                          20
       FDB    SZTHR    THRUST               42                          21
       FDB    SZSB     SMART BOMB           43                          22
       FDB    SZHYP    HYPER SPACE          44                          23
       FDB    SZS2     START 2              45                          24
       FDB    SZS1     START 1              46                          25
       FDB    SZREV    REVERSE              47                          26
       FDB    SZDOWN   DOWN                 48                          27
       FDB    SZUP     UP                   49                          28
       FDB    SZINV    INVISO               50                          29
       FDB    CRTSTP   COLOR MATRIX TEST    51                          30
       FDB    BOOKMP   BOOKKEEPING          52                          31
       FDB    AZS1     LEFT SLOT            53                          32
       FDB    AZS2     CENTER SLOT          54                          33
       FDB    AZS3     RIGHT SLOT           55                          34
       FDB    AZPDC    PAID CREDITS         56                          35
       FDB    AZFS     FREE SHIPS           57                          36
       FDB    AZTIM    TOTAL PLAY TIME      58                          37
       FDB    AZSHIP   TOTAL SHIP COUNT     59                          38
       FDB    AZPLAY   TOTAL PLAYS          60                          39
       FDB    GOMP     GAME OVER                                        40
       FDB    AUD1P    HIGH OF 6 DIG        62                          41
       FDB    AUD2P    LOW OF 6 DIG         63                          42
       FDB    AUD3P    4 DIG                64                          43
       FDB    FROBMP   FROB                       65                    44
       FDB    CONTMP   CONTINUED ON NEXT PAGE     66                    45
       FDB    JZREP    REPLAY ADJUSTMENT          67                    46
       FDB    JZSHP    1 CRED SHIPS               68                    47
       FDB    JZCONS   COIN SELECT                70                    48
       FDB    JZSL1    SLOT 1                     71                    49
       FDB    JZSL2    SLOT 2                     72                    50
       FDB    JZSL3    SLOT 3                     73                    51
       FDB    JZCUC    CREDIT UNIT                74                    52
       FDB    JZCUB    BONUS UNIT                 75                    53
       FDB    JZMUN    MINIMUM UNITS NEEDED       76                    54
       FDB    JZFREE   FREE PLAY                  77                    55
       FDB    JZMASA   MASTER ADJUST              78                    56
       FDB    JZGODL   GOD LETTERS                87                    57
       FDB    JZFACS   FACTORY SETTINGS           88                    58
       FDB    JZCAUD   CLEAR AUDIT                89                    59
       FDB    JZCLHS   CLEAR HIGH SCORES          90                    60
       FDB    JZAUTO   AUTO CYCLE                 91                    61
       FDB    JZOPM    OPERATOR MESSAGE           92                    62
       FDB    JZGOD    LETTERS IN GOD             93                    63
       FDB    REPMS1   REPLAY MESSAGE 1           94                    64
       FDB    REPMS2                              95                    65
       FDB    NOMESP   JUST THE NUMBER            96                    66
       FDB    HIVOLP   HI VOLUME ARCADE           97                    67
       FDB    RECOMP   RECOMMENDED SETTING        98                    68
       FDB    POORPP   WEAK PLAYER SETTING        99                    69
       FDB    CUSTMP   CUSTOM SETTINGS           100                    70
       FDB    YESMP    YES ONLY                  101                    71
       FDB    NOMP     NO ONLY                   102                    72
       FDB    EXLIBP   EXTRA LIBERAL             103                    73
       FDB    LIBP                               104                    74
       FDB    PGOMP   PLAYER X GAME OVER         105                    75
       FDB    CONSP                              106                    76
       FDB    EXCONP                             107                    77
       FDB    REPMS3   REPLAY MESSAGE 3          108                    78
       FDB    CMIMEP                             109                    79
       FDB    RESMSP                             110                    80
       FDB    YES1MP                             111                    81
       FDB    COIN1P                             112                    82
       FDB    COIN2P                             113                    83
       FDB    COIN3P                             114                    84
       FDB    COIN4P                             115                    85
       FDB    COIN5P                             116                    86
       FDB    COIN6P                             117                    87
       FDB    COIN7P                             118                    88
       FDB    COIN8P                             119                    89
       FDB    NOREPP                             120                    90
       FDB    BOOKRP                             121                    91
       FDB    OPMESP                             125                    92
       FDB    HSRESP                             126                    93
       FDB    GODMSP                             135                    94
       FDB    CONGP                              136                    95 
       FDB    NOWMSP                             137                    96
       FDB    HSINDP                             139                    97
       FDB    HIGH1P                             140                    98
       FDB    HIGH3P                             141                    99
       FDB    ONLY5P                             148                   100
       FDB    CENTRP                             149                   101
       FDB    REPMS4                                                   102
       FDB    PLUPP    PLAYER X UP                                     103
       FDB    WAVEP    WAVE NUMBER                                     104
       FDB    INDMFP                                                   105
       FDB    AVM1                                                     106
       FDB    AVM2                                                     107
       FDB    AVM3                                                     108
       FDB    AVM4                                                     109
       FDB    SCRMEP                                                   110
       FDB    INDMEP                                                   111
       FDB    CPYM1                                                    112
       FDB    CPYM2                                                    113
       FDB    WAVEM2                                                   114
       FDB    PMOM
       FDB    PDAD
       FDB    PKID
       FDB    PGRUNT
       FDB    PHULK
       FDB    PSPCU
       FDB    PENTK
       FDB    PBRAIN
       FDB    COINF                                                    123
       FDB    PPROG
       FDB    EXMANN                                                   125
       FDB    NULM                                                     126
       FDB    CRDM22
       FDB    TITLEP                                                   128
       FDB    FAMMP                                                    129

SCRMEP FCB    COLOR,$77,CURSAB,$35,$25,0,SUB
       FDB    ROHSUB
       FCC    'ES'
       FCB    CURSAB,$35,$6E,0
       FCC    'ALL '            
       FCB    CURSOR,0,0,1 
       FCC    'TIME '
       FCB    CURSOR,1,0,0
       FCC    'HEROES'
NULM   FCB    0

ROHSUB FCC    'ROBOTRON HERO'
       FCB    0

INDMEP FCB    SBLANK,NUMB,RPAREN,SPACE,0

CENTRP FCB    COLOR,$99,CURSAB,$25,$70,1
       FCC    'CENTER THE LINE USING '               
       FCB    HYPHEN
       FCC    'FIRE'
       FCB    HYPHEN,CURSAB,$24,$7E,1
       FCB    SUB
       FDB    PASUB   'PRESS ADVANCE '
       FCC    'WHEN CENTERED'
       FCB    COLOR,$BB,SFONT,CURSAB,$49,$50,1,ARROW
       FCB    0

PASUB  FCC    'PRESS ADVANCE '
       FCB    0

PESUB  FCB    SUB
       FDB    PASUB
       FCC    'TO EXIT'
       FCB    0

OPMESP FCB    COLOR,$BB,CURSAB,$2E,$16,0,SUB
       FDB    AMSUB
       FCB    SUB  
       FDB    TELSUB
       FCB    0

ONLY5P FCB    COLOR,$BB,CURSAB,$20,$70,0
       FCC    '5 ENTRIES MAXIMUM'            
       FCB    SUB
       FDB    PPSUB
       FCB    CURSAB,$28,$90,1
       FCC    'LOWEST ENTRY REPLACED'
       FCB    0

TELSUB FCB    SFONT,COLOR,$99,CURSAB,$2F,$C0,1
       FCB    SUB
       FDB    UPDNSB
       FCC    'LETTER'
       FCB    CURSAB,$32,$CC,0
       FCB    HYPHEN
       FCC    'FIRE UP'
       FCB    HYPHEN
       FCC    ' TO ENTER LETTER'
       FCB    COLOR,$44
       FDB    0

PRPLYR FCB    CURSAB,$40,$10,$0
PLRSUB FCC    'PLAYER '
       FCB    0

GODMSP FCB    COLOR,$BB,SUB               
       FDB    PRPLYR    
       FCB    ZBLANK,NUMY,CURSAB,$2C,$28,0
       FCC    'YOU ARE THE GREATEST'               
       FCB    CURSAB,$36,$38,0,SUB
       FDB    ROHSUB
       FCB    CURSAB,$34,$58,0,SUB
       FDB    ENTSSB
       FCC    'NAME'
       FCB    CURSAB,$31,$68,0,LPAREN
       FCC    'UP TO '
       FCB    ZBLANK,NUMB
       FCC    ' LETTERS'
       FCB    RPAREN,SUB
       FDB    TELSUB
       FCB    0

ENTSSB FCC    'ENTER YOUR '
       FCB    0

CONGP  FCB    COLOR,$44,SUB      
       FDB    PRPLYR
       FCB    ZBLANK,NUMB
       FCB    CURSAB,$29,$30,0
       FCC    'YOU ARE A '                 
       FCB    SUB
       FDB    ROHSUB
NOWSUB FCB    CURSAB,$2D,$58,1,SUB
       FDB    ENTSSB
       FCC    'INITIALS'
       FCB    COLON,SUB
       FDB    TELSUB
       FCB    0

NOWMSP FCB    COLOR,$99,SUB
       FDB    PRPLYR
       FCB    ZBLANK,NUMB
       FCB    CURSAB,$43,$67,0
       FCC    'ALSO'
       FCB    SUB
       FDB    NOWSUB
       FCB    0

HSINDP FCB    SBLANK,NUMB,RPAREN,SPACE,SPACE,0

HIGH1P FCB    SBLANK,NUMY,0

HIGH3P FCB    CURSOR,$8,0,0,SBLANK,NUMY,0

REPMS1 FCB    SBLANK,NUMB 
       FCC    '000  '       
LIBS   FCC    'LIBERAL'
       FCB    0

REPMS2 FCB    SBLANK,NUMB
       FCC    '000  '               
RECS1  FCC    'RECOMMENDED'
       FCB    0

REPMS3 FCB    SBLANK,NUMB
       FCC    '000  '                
CONSUB FCC    'CONSERVATIVE'
       FCB    0

REPMS4 FCB    SBLANK,NUMB
       FCC    '000  EXTRA '              
       FCB    SUB
       FDB    CONSUB
       FCB    0

SPSUB  FCB    CURSOR,8,0,0        MOVE 8 FULL BYTES TO THE RIGHT
       FCB    0

RECS2  FCB    SUB
       FDB    SPSUB
       FCB    SUB
       FDB    RECS1
       FCB    0

NOMESP FCB    SBLANK,NUMB,0

HIVOLP FCB    SUB
       FDB    SVSUB
       FCC    'HIGH VOLUME ARCADES'
       FCB    0

RECOMP FCB    SBLANK,NUMB,SUB
       FDB    RECS2
       FCB    0

POORPP FCB    SUB
       FDB    SVSUB
       FCC    'FOR WEAKER PLAYERS'
       FCB    0

CUSTMP FCB    SUB
       FDB    SVSUB
       FCC    'CUSTOM '
       FCB    HYPHEN,SPACE,LPAREN
       FCC    'ADJUST BELOW'
       FCB    RPAREN,0
YES1MP FCC    'YES'
       FCB    SUB
       FDB    SPSUB
       FCB    CURSOR,-2,0,0 ALLOW FOR EXTRA LETTER 'S'
       FCC    'ADVANCE TO ACTIVATE'
       FCB    0

SVSUB  FCB    SBLANK,NUMB,SUB
       FDB    SPSUB
       FCB    0

YESMP  FCC    'YES'
       FCB    0

NOMP   FCC    'NO'
       FCB    0


EXLIBP FCB    SUB    
       FDB    EXSBB
       FCB    SUB
       FDB    LIBS
       FCB    0

EXSBB  FCB    SUB
       FDB    SVSUB
       FCC    'EXTRA '
       FCB    0

LIBP   FCB    SUB
       FDB    SVSUB
       FCB    SUB
       FDB    LIBS
       FCB    0

CONSP  FCB    SUB
       FDB    SVSUB
       FCB    SUB
       FDB    CONSUB
       FCB    0

EXCONP FCB    SUB
       FDB    EXSBB
       FCB    SUB
       FDB    CONSUB
       FCB    0

NOREPP FCB    SUB
       FDB    SVSUB
       FCC    'NO EXTRA MEN'
       FCB    0  

COIN1P FCB    SUB  
       FDB    SVSUB
       FCC    '1'  
       FCB    SLASH  
       FCC    'FIFTY  3'
       FCB    SLASH 
       FCC    'DOLLAR'
       FCB    0

COINF  FCB    SUB
       FDB    SVSUB
       FCC    'FREE PLAY'
       FCB    0

COIN2P FCB    SUB
       FDB    SVSUB
       FCC    '1'           
       FCB    SLASH 
       FCC    '1 DM  6'
       FCB    SLASH 
       FCC    '5 DM'
       FCB    0

COIN3P FCB    SUB
       FDB    SVSUB
       FCC    '1'                
       FCB    SLASH 
       FCC    'QUARTER  4'
       FCB    SLASH 
       FCC    'DOLLAR'
       FCB    0

COIN4P FCB    SUB
       FDB    SVSUB
       FCC    '1'           
       FCB    SLASH 
       FCC    '2 F  3'
       FCB    SLASH 
       FCC    '5 F'
       FCB    0

COIN5P FCB    SUB
       FDB    SVSUB
       FCC    '1'
       FCB    SLASH 
       FCC    'FIFTY  2'
       FCB    SLASH 
       FCC    'DOLLAR'
       FCB    0

COIN6P FCB    SUB 
       FDB    SVSUB
       FCC    '1'              
       FCB    SLASH 
       FCC    '25  4'
       FCB    SLASH 
       FCC    '1 G'
       FCB    0

COIN7P FCB    SUB
       FDB    SVSUB
       FCC    '1'         
       FCB    SLASH 
       FCC    '5 F  2'
       FCB    SLASH 
       FCC    '10 F'
       FCB    0

COIN8P FCB    SUB
       FDB    SVSUB
       FCC    '1'
       FCB    SLASH 
       FCC    '10 F'
       FCB    0

CMIMEP FCB    COLOR,$11,CURSAB,$30,$80,0,SUB
       FDB    ADJS
       FCC    ' FAILURE'
       FCB    CURSAB,$20,$A0,0    
       FCC    'RESTORE'
       FCB    SUB
       FDB    FACSUB
       FCC    'BY'
       FCB    CURSAB,$20,$B0,0,SUB
       FDB    CMISUB
       FCB    COKSUB
       FDB    CMICOK
       FCB    CURSAB,$20,$C0,0
       FCC    'AND TURNING GAME OFF AND ON'         
       FCB    0

FACSUB FCC    ' FACTORY SETTINGS '
       FCB    0

RESMSP FCB    COLOR,$99,CURSAB,$21,$80,0,SUB
       FDB    FACSUB
       FCC    ' RESTORED'
       FCB    0

CMISUB FCC    'OPENING '           
FDORSB FCC    'FRONT DOOR'
       FCB    0

CMICOK FCB    CURSAB,$20,$B0,0,COLOR,$00,SUB
       FDB    CMISUB 
       FCB    CURSAB,$20,$B0,0,COLOR,$11
       FCC    'RAISING '          
TABLSB FCC    'TABLE TOP'
       FCB    0

FROBMP FCB    COLOR,$99,FROB,COLOR,$66,0   DISPLAY FROB

CONTMP FCB    LFONT,COLOR,$99,CURSAB,$37,$0F,0
       FCC    'GAME '
       FCB    SUB
       FDB    ADJS
       FCB    SFONT,CURSAB,$2E,$CD,0,COLOR,$99,SUB
       FDB    UPDNSB
       FCB    SUB
       FDB    ADJS
       FCB    CURSAB,$2B,$D5,0
       FCC    'USE '
       FCB    HYPHEN
       FCC    'FIRE'
       FCB    HYPHEN
       FCC    ' LEVER TO CHANGE THE VALUE'
       FCB    CURSAB,$39,$E2,0,COLOR,$55,SUB
       FDB    PESUB
       FCB    0

ADJS   FCC    'ADJUSTMENT'
       FCB    0

UPDNSB FCC    'USE '     
       FCB    HYPHEN
       FCC    'MOVE'
       FCB    HYPHEN
       FCC    ' TO SELECT '
       FCB    0

EXMANN FCB    COLOR,$66,CURSAB,$36,$EE,0,SUB
       FDB    JZREP
       FCB    SPACE,NUMB
       FCC    '000'
       FCB    0

JZREP  FCC    'EXTRA MAN EVERY'
       FCB    0

JZSHP  FCC    'TURNS'           
PPSUB  FCC    ' PER '       
       FCB    SUB
       FDB    PLRSUB
       FCB    0 

JZCONS FCC    'PRICING SELECTION'
       FCB    0

JZSL1  FCC    'LEFT'
       FCB    SUB
       FDB    SLSUB
       FCB    0

JZSL2  FCC    'CENTER'
       FCB    SUB
       FDB    SLSUB
       FCB    0

JZSL3  FCC    'RIGHT'
       FCB    SUB
       FDB    SLSUB
       FCB    0   

SLSUB  FCC    ' SLOT UNITS'
       FCB    0

JZCUC  FCB    SUB         
       FDB    UNFOR
       FCC    'CREDIT'
       FCB    0

JZCUB  FCB    SUB
       FDB    UNFOR
       FCC    'BONUS CREDIT'
       FCB    0

JZMUN  FCC    'MINIMUM UNITS FOR ANY CREDIT'
       FCB    0

UNFOR  FCC    'UNITS REQUIRED FOR '
       FCB    0

JZFREE FCC    'FANCY ATTRACT MODE'
       FCB    0

JZMASA FCC    'DIFFICULTY OF PLAY'
       FCB    0

JZGODL FCC    'LETTERS FOR'              
       FCB    SUB
       FDB    HISCR
       FCB    0

HISCR  FCC    ' HIGHEST SCORE NAME'
       FCB    0

JZFACS FCC    'RESTORE'                 
       FCB    SUB
       FDB    FACSUB
       FCB    0

JZCAUD FCC    'CLEAR'                     
       FCB    SUB
       FDB    BKTSUB
       FCB    0

JZCLHS FCC    'HIGH SCORE TABLE RESET'
       FCB    0

JZAUTO FCC    'AUTO CYCLE'
       FCB    0

JZOPM  FCC    'SET '                         
AMSUB  FCC    'ATTRACT MODE MESSAGE'
       FCB    0

JZGOD  FCC    'SET'
       FCB    SUB
       FDB    HISCR
       FCB    0

AUD1P  FCB    SBLANK,NUMB,0              SETUP SKIP-BLANKING

AUD2P  FCB    NBLANK,NUMY,0              NO BLANKING ON THIS PART

AUD3P  FCB    CURSOR,6,0,0              MOVE 2 CHARACTERS RIGHT
       FCB    SBLANK,NUMY,0              THEN PRINT NUMBER WITH SPACING

BOOKMP FCB    CURSAB,$2F,$10,0
       FCB    COLOR,$99,SUB
       FDB    BKTSUB
       FCB    COLOR,$11,0

BOOKRP FCB    CURSAB,$20,$60,0
       FCB    COLOR,$33,SUB
       FDB    BKTSUB
       FCC    'CLEARED'
       FCB    0

HSRESP FCB    CURSAB,$2A,$40,0
       FCB    COLOR,$88,SUB
       FDB    JZCLHS
       FCB    0

BKTSUB FCC    ' BOOKKEEPING TOTALS '
       FCB    0

AUDX1  EQU    $1C
AUDX2  EQU    $6C

AZPDC  FCB    CURSAB,AUDX1,$60,0
       FCC    'PAID CREDITS'
       FCB    CURSAB,AUDX2,$60,0,0

AZFS   FCB    CURSAB,AUDX1,$70,0
       FCC    'EXTRA MEN EARNED'   
       FCB    CURSAB,AUDX2,$70,0,0

AZTIM  FCB    CURSAB,AUDX1,$80,0
       FCC    'PLAY TIME IN MINUTES'
       FCB    CURSAB,AUDX2,$80,0,0

AZSHIP FCB    CURSAB,AUDX1,$90,0
       FCC    'MEN PLAYED'
       FCB    CURSAB,AUDX2,$90,0,0

AZPLAY FCB    CURSAB,AUDX1,$A0,0
       FCC    'CREDITS PLAYED'
       FCB    CURSAB,AUDX2,$A0,0,0

AVM1   FCB    CURSAB,AUDX1,$C0,0
       FCC    'AVERAGE TIME PER CREDIT'
       FCB    CURSAB,AUDX2-8,$C0,0,0

AVM2   FCB    COLON,NBLANK,NUMB,0

AVM3   FCB    CURSAB,AUDX1,$D0,0
       FCC    'AVERAGE TURNS PER CREDIT'
       FCB    CURSAB,AUDX2-8,$D0,0,0

AVM4   FCB    PERIOD,NBLANK,NUMB,0

AZS1   FCB    CURSAB,AUDX1,$30,0
       FCC    'LEFT'
       FCB    SUB
       FDB    COINSB
       FCB    CURSAB,AUDX2,$30,0,0

AZS2   FCB    CURSAB,AUDX1,$40,0
       FCC    'CENTER'
       FCB    SUB
       FDB    COINSB
       FCB    CURSAB,AUDX2,$40,0,0

AZS3   FCB    CURSAB,AUDX1,$50,0
       FCC    'RIGHT'
       FCB    SUB
       FDB    COINSB
       FCB    CURSAB,AUDX2,$50,0,0

COINSB FCC    ' SLOT COINS'
       FCB    0

CRTSTP FCB    COLOR,$33,CURSAB,$3A,$80,0
       FCC    'COLOR RAM TEST'
       FCB    CURSAB,$27,$B0,0
       FCC    'VERTICAL BARS INDICATE ERROR'
       FCB    0

SZAUP  FCC    'AUTO UP'
       FCB    0

SZADV  FCC    'ADVANCE'
       FCB    0

SZRC   FCC    'RIGHT COIN'
       FCB    0

SZHSR  FCC    'HIGH SCORE RESET'
       FCB    0

SZLC   FCC    'LEFT COIN'
       FCB    0

SZCC   FCC    'CENTER COIN'
       FCB    0

SZSS   FCC    'SLAM SWITCH'
       FCB    0

SZFIRE FCC    'MOVE UP'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZTHR  FCC    'MOVE DOWN'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZSB   FCC    'MOVE LEFT' 
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZHYP  FCC    'MOVE RIGHT'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZS2   FCC    '1'             
       FCB    SUB
       FDB    PSTSUB
       FCB    0

SZS1   FCC    '2'
       FCB    SUB      
       FDB    PSTSUB
       FCB    0

PSTSUB FCB    SPACE,SUB
       FDB    PLRSUB
       FCC    'START'
       FCB    0

SZREV  FCC    'FIRE UP'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZDOWN FCC    'FIRE DOWN'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZUP   FCC    'FIRE LEFT'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

SZINV  FCC    'FIRE RIGHT'
       FCB    COKSUB
       FDB    PLYSUB
       FCB    0

PLYSUB FCC    '  '
       FCB    LPAREN,SUB
       FDB    PLRSUB
       FCB    ZBLANK,NUMB,RPAREN,0

SWTSTP FCB    COLOR,$88,CURSAB,$3A,26,0
       FCC    'SWITCH TEST'
       FCB    0

ROMOKP FCB    COLOR,$99,CURSAB,$3E,$50,$0
       FCC    'ALL ROMS OK'
       FCB    CURSAB,$36,$90,0,COLOR,$33
       FCC    'RAM TEST FOLLOWS'
       FCB    SUB
       FDB    ROKSB
       FCB    0

ROKSB  FCB    CURSAB,$2F,$A0,0,SUB
       FDB    PESUB
       FCB    0

RAMSUB FCC    ' RAM ERRORS DETECTED'
       FCB    0

RAMOKP FCB    COLOR,$99,CURSAB,$2A,$80,0
       FCC    'NO'
       FCB    SUB
       FDB    RAMSUB
       FCB    0

CMOKP  FCB    COLOR,$99,CURSAB,$23,$80,0
       FCC    'NO CMOS' 
       FCB    SUB
       FDB    RAMSUB
       FCB    0

CMSUB  FCC    'CMOS RAM'
       FCB    SUB
       FDB    ERRSUB
       FCB    0

CMERRP FCB    COLOR,$11,CURSAB,$36,$80,0
       FCB    SUB              
       FDB    CMSUB
       FCB    0

CMDORP FCB    SUB                        
       FDB    CMERRP
       FCB    CURSAB,$28,$90,0
       FCC    'OR WRITE PROTECT FAILURE'
       FCB    COLOR,$99,SUB    
       FDB    FDSUBB
       FCB    COKSUB
       FDB    FDCOCK
       FCB    0

FDCOCK FCB    COLOR,$00,SUB
       FDB    FDSUBB
       FCB    COLOR,$99,CURSAB,$17,$B0,0,HYPHEN,SUB
       FDB    TABLSB
MBOSUB FCC    ' MUST BE OPEN FOR TEST'
       FCB    HYPHEN,0

FDSUBB FCB    CURSAB,$1B,$B0,0,HYPHEN,SUB
       FDB    FDORSB
       FCB    SUB
       FDB    MBOSUB
       FCB    0

SNDTEP FCB    COLOR,$00,CURSAB,$57,$80,0
       FCB    BLANKR                        BLANK OUT THE LAST ONE
       FCB    COLOR,$99,CURSAB,$3A,$80,0
       FCC    'SOUND LINE '
       FCB    ZBLANK,NUMB,0
 FCB PERIOD,SPACE,SPACE

INSUB  FCB    CURSAB,$30,$70,0                           
       FCC    'INITIAL TESTS INDICATE'
       FCB    COLON,0

INDMFP FCB    COLOR,$11,SUB
       FDB    INSUB
       FCB    CURSAB,$3C,$90,0
       FCB    SUB
       FDB    BADDMP
       FCB    0

OKMP   FCB    COLOR,$99,SUB
       FDB    INSUB                   
       FCB    CURSAB,$3F,$90,1
       FCC    'OPERATIONAL'   
       FCB    0

INERSB FCB    COLOR,$11,SUB          IN RED,
       FDB    INSUB                  INITIAL TESTS INDICATE,
       FCB    CURSAB,$40,$90,0,0     AND SET CURSOR FOR ERROR

       FCC    ' (C) 1982 WILLIAMS ELECTRONICS INC. '

FDSUB  FCB    CURSAB,$40,$80,0
       FCB    COLOR,$11
       FCB    0

BADDMP FCB    SUB
       FDB    FDSUB
       FCB    CURSOR,-30,0,0      RELATIVE CURSOR MOVE
       FCC    'SPECIAL CHIP FAILURE'
       FCB    0          PRINT IT 

FDROMP FCB    SUB
       FDB    FDSUB
       FCC    'ROM'
       FCB    SUB
       FDB    ERRSUB
       FCB    NUMB,0

FDRAMP FCB    SUB
       FDB    FDSUB
       FCC    'RAM'
       FCB    SUB
       FDB    ERRSUB
       FCB    NUMB,0

ROMERP FCB    SUB
       FDB    INERSB
       FCC    'ROM'
       FCB    SUB
       FDB    ERRSUB
       FCB    NUMB,0

RERRMP FCB    SUB    
       FDB    INERSB
       FCC    'RAM'
       FCB    SUB
       FDB    ERRSUB
       FCB    NUMB,0

ERRSUB FCC    ' ERROR '
       FCB    ZBLANK,0

CPYM1  FCB    COLOR,$AA,CURSAB,$24,$C8,0,SUB
       FDB    CPYSUB
       FCB    COLOR,$66,CURSAB,$38,$B5,0
       FCC    'DESIGNED BY VID KIDZ'
       FCB    CURSAB,$2E,$BC,0
       FCC    'FOR '                        
       FCB    SUB
       FDB    WNAMES
       FCB    COLOR,$22,CURSAB,$3D,$A8,0,LFONT
CDDSUB FCC    'CREDITS'
       FCB    COLON,SPACE,ZBLANK,NUMB
       FCB    0

CRDM22 FCB    COLOR,$AA,CURSAB,$41,$EE,0
       FCB    SUB
       FDB    CDDSUB
       FCB    0

CPYM2  FCB    CURSAB,$24,$EE,0
CPYSUB FCC    'COPYRIGHT 1982 '                         
WNAMES FCC    'WILLIAMS ELECTRONICS INC'
       FCB    PERIOD
       FCB    0

GOMP   FCB    CURSAB,$3E,$80,0
GOSUBB FCC    'GAME OVER'
       FCB    0

PGOMP  FCB    CURSAB,$3F,$79,1,SUB 
       FDB    PLSUB
       FCB    CURSAB,$3E,$86,0,SUB
       FDB    GOSUBB
       FCB    0

PLUPP  FCB    CURSAB,$3F,$7A,1
PLSUB  FCB    SUB
       FDB    PLRSUB
       FCB    ZBLANK,NUMB,0

WAVEP  FCB    CURSAB,$3E,$EE,0,SBLANK,COLOR,$AA
       FCB    NUMB,CURSOR,3,0,0,COLOR,$BB
       FCC    ' WAVE' 
       FCB    0            

WAVEM2 FCB    CURSOR,$04,$00,0,ZBLANK,COLOR,$AA
       FCB    NUMB,0

PMOM   FCC    'MOMMY'            
       FCB    0

PGRUNT FCC    'GRUNT '
       FCB    HYPHEN
       FCC    ' 100'
       FDB    0

PDAD   FCC    'DADDY' 
       FCB    0

PKID   FCC    'MIKEY'
       FCB    0

PHULK  FCC    'INDESTRUCTABLE HULK'         
       FCB    0

PSPCU  FCC    'SPHEREOID '
       FCB    HYPHEN
       FCC    ' 1000     QUARK '
       FCB    HYPHEN
       FCC    ' 1000'
       FCB    0

PENTK  FCC    'ENFORCER '
       FCB    HYPHEN
       FCC    ' 150   TANK '
       FCB    HYPHEN
       FCC    ' 200'
       FCB    0

PBRAIN FCC    'BRAIN '
       FCB    HYPHEN
       FCC    ' 500     CRUISE MISSILE '
       FCB    HYPHEN
       FCC    ' 25'
       FCB    0

PPROG  FCC    'PROG '
       FCB    HYPHEN
       FCC    ' 100'
       FCB    0

TITLEP FCB    COLOR,$AA,CURSAB,$36,$24,0
       FCC    'ROBOTRON'     
       FCB    COLON,SPACE
       FCC    '2084'
       FCB    0

FAMMP  FCB    COLOR,$AA,CURSAB,$25,$84,0
       FCC    'SAVE THE LAST HUMAN FAMILY'
       FCB    0

